resume = true

batch_size=32
fs = 16000
train_seq_duration = 4.0
lr_start = 0.0003
lr_stop = 0.00001
validate_only = false
val_interval = 20000
max_steps = 500000
num_workers = 14
data_distribution_seed = 1

[model]
hopsize = 80
winlen = 320
method = "time_domain_filtering"
num_filter_frames = 1
learnable_transforms = true
algorithmic_delay_nn=40
algorithmic_delay_filtering=40
adaptive_phase_shift=false
linphase_regressor_hidden_size=1


[model.crn_config]
num_channels_encoder = [2, 16, 32, 48, 64]
kernel_sizes = [[5, 3], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3], [1, 3]]
fstride = 2
n_gru_layers = 1
n_gru_groups = 4
nonlinearity = "ELU"
batch_norm = false

[loss]
winlen = 320
complex_weight = 0.3
f_fade_out_complex_low = 3000
f_fade_out_complex_high = 4500

[data_distribution]
snr_mu_and_sigma=[15, 10]
speech_rms_mu_and_sigma=[-20, 7]
apply_noise=true
rir_percentage=0.75







